AllCops:
  Exclude:
    - '*.gemspec'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Rakefile'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/LineLength:
  Max: 150
  Exclude:
    - "spec/**/*"

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: true

Style/StringLiterals:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false