---
key1:
  value: '100'
  conditions:
    condition1:
      value: '200'
    zxczx:
      value: '100'
key2:
  value: '123'
key3:
  value: 'true'
key4:
  value: 'false'
key5:
  value: xxxx
key6:
  value: '{"value":"xxxx"}'
key7:
  value: '{"x1":"x1","x2":"x2"}'
